name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:

  build:
    environment: production_environment
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # node: [12, 14]
        node: [14]
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - name: ♻️ Clone repository
        uses: actions/checkout@v2

      - name:	🔖  Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ⬇️  Install npm dependencies
        run: npm install # switch to `npm ci` when Node.js 6 support is dropped

      - name: ✅  Run tests
        run: npm run test

      - name: 🏗️  Build
        run: npm run build

  # https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 💯 Generate test coverage report
        run: |
          # var SUMMARY = [
          #   '',
          #   '=============================== Coverage summary ===============================',
          #   'Statements   : 32.5% ( 39/120 )',
          #   'Branches     : 38.89% ( 21/54 )',
          #   'Functions    : 21.74% ( 5/23 )',
          #   'Lines        : 31.93% ( 38/119 )',
          #   '================================================================================',
          #   ''
          # ];
          # SUMMARY = SUMMARY.split('\n')[5]; // 'Lines        : 31.93% ( 38/119 )'
          # SUMMARY = SUMMARY.split(':')[1].split('(')[0].trim(); // '31.93%'
          SUMMARY="$(npm test -- --coverageReporters='text-summary' | tail -2 | head -1)"
          TOKENS=($SUMMARY)
          # process.env.COVERAGE = '31.93%';
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
          # var REF = 'refs/pull/27/merge.json';
          REF=${{ github.ref }}
          # console.log('github.ref: ' + REF);
          echo "github.ref: $REF"
          # var PATHS = REF.split('/');
          IFS='/' read -ra PATHS <<< "$REF"
          # var BRANCH_NAME = PATHS[1] + PATHS[2];
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          # console.log(BRANCH_NAME); // 'pull_27'
          echo $BRANCH_NAME
          # process.env.BRANCH = 'pull_27';
          echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
      - name: 📛 Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 7d4c25ef2e97e8de523ef7c1fee26e8e
          filename: your-repo-name__${{ env.BRANCH }}.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: jest
          parallel-finished: true


#    # Main doesn't have a PR for comments so skip that branch
#     # We don't want multiple comments about code coverage, just just run it once on 14.x on Linux
#     - if: ${{ github.ref != 'refs/heads/main' && matrix.node-version == '14.x' && matrix.os == 'ubuntu-latest' }}
#       uses: romeovs/lcov-reporter-action@v0.2.16
#       with:
#         github-token: ${{ secrets.GITHUB_TOKEN }}
#         lcov-file: ./tests/coverage/lcov.info
