name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:

  test:
    environment: production_environment
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # node: [12, 14]
        node: [14]
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - name: ♻️ Clone repository
        uses: actions/checkout@v2

      - name:	🔖  Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ⬇️  Install npm dependencies
        uses: c-hive/gha-npm-cache@v1
        run: npm install # switch to `npm ci` when Node.js 6 support is dropped

      - name: ✅  Run tests
        run: npm run test
